export const routeTranslations = {
  en: {
    about: "about",
    contact: "contact",
    divisions: "divisions",
    solutions: "solutions",
    technology: "technology",
    career: "careers",
    apply: "apply",
    news: "news",
    robotics: "robotics",
    production_house: "production_house",
    insurtech: "insurtech",
    fnb: "fnb",
    ai_ondemand: "ai_ondemand",
    cloud_computing: "cloud_computing",
    big_data: "big_data",
    automation: "automation",
    digital_maps: "digital_maps",
    golf_technology: "golf_technology",
    app_development: "app_development",
    ecommerce: "ecommerce",
    investment_venture: "investment_venture",
  },
  vi: {
    about: "ve_chung_toi",
    contact: "lien_he",
    divisions: "cac_bo_phan",
    solutions: "giai_phap",
    technology: "cong_nghe",
    apply: "ung_tuyen",
    career: "tuyen_dung",
    news: "tin_tuc",
    robotics: "robotic",
    production_house: "bo_phan_san_pham",
    insurtech: "cong_nghe_bao_hiem",
    fnb: "tieu_dung_nhanh",
    investment_venture: "dau_tu_khoi_nghiep",
    ai_ondemand: "tri_tue_nhan_tao_tuc_thoi",
    cloud_computing: "dien_toan_dam_may",
    big_data: "du_lieu_lon",
    automation: "tu_dong_hoa",
    digital_maps: "ban_do_so",
    golf_technology: "cong_nghe_golf",
    app_development: "phat_trien_ung_dung",
    ecommerce: "thuong_mai_dien_tu",
  },
  zh: {
    about: "guan_yu_wo_men",
    contact: "lian_xi_wo_men",
    divisions: "ye_wu_bu_men",
    solutions: "wo_men_de_jie_jue_fang_an",
    technology: "ji_shu",
    career: "zhi_ye_fa_zhan",
    news: "xin_wen",
    apply: "shen_qing",
    robotics: "ji_qi_ren_ke_ji",
    production_house: "zhi_zuo_gong_zuo_shi",
    insurtech: "bao_xian_ke_ji",
    fnb: "yin_shi",
    investment_venture: "tou_zi_qi_ye",
    ai_ondemand: "zhi_neng_xu_qiu",
    cloud_computing: "yun_ji_suan",
    big_data: "da_shu_ju",
    automation: "zi_dong_hua",
    digital_maps: "shu_zi_di_tu",
    golf_technology: "gao_er_fu_ke_ji",
    app_development: "ying_yong_kai_fa",
    ecommerce: "dian_shang",
  },
};

export const careerRoutes = [
  { lang: 'en', slug: 'careers', segment: 'apply' },
  { lang: 'vi', slug: 'tuyen_dung', segment: 'ung_tuyen' },
  { lang: 'zh', slug: 'zhi_ye_fa_zhan', segment: 'shen_qing' },
];

export const divisionsRoutes = [
  { lang: 'en', slug: 'divisions' },
  { lang: 'vi', slug: 'phong_ban' },
  { lang: 'zh', slug: 'bu_men' },
];

export const solutionsRoutes = [
  { lang: 'en', slug: 'solutions' },
  { lang: 'vi', slug: 'giai_phap' },
  { lang: 'zh', slug: 'jie_jue_fang_an' },
];

export const newsRoutes = [
  { lang: 'en', slug: 'news' },
  { lang: 'vi', slug: 'tin_tuc' },
  { lang: 'zh', slug: 'xin_wen' },
];
